#include <common/types/enums.h>
G_DEFINE_ENUM_TYPE(
	PlanifiedTimePrecision, planified_time_precision,
	G_DEFINE_ENUM_VALUE(PLANIFIED_TIME_PRECISION_YEAR,"year"),
	G_DEFINE_ENUM_VALUE(PLANIFIED_TIME_PRECISION_MONTH,"month"),
	G_DEFINE_ENUM_VALUE(PLANIFIED_TIME_PRECISION_WEEK,"week"),
	G_DEFINE_ENUM_VALUE(PLANIFIED_TIME_PRECISION_DAY,"day"),
	G_DEFINE_ENUM_VALUE(PLANIFIED_TIME_PRECISION_HOUR,"hour"),
	G_DEFINE_ENUM_VALUE(PLANIFIED_TIME_PRECISION_MINUTE,"minute"),
	G_DEFINE_ENUM_VALUE(PLANIFIED_TIME_PRECISION_SECOND,"second")
)